[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    'node_modules/@layerzerolabs/toolbox-foundry/lib', 
    'node_modules', 
]
solc = "0.8.28"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/', 
    '@prb-math/=lib/prb-math/src/', 
    "@murky/=lib/murky/src/",
    '@forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    '@stargatefinance/=node_modules/@stargatefinance/'
]

via_ir = true
ir-minimum=true
optimizer = true
optimizer_runs = 200

gas_reports = ["*"]

[profile.ci]
via_ir = true
# ir-minimum=true
optimizer = true
optimizer_runs = 200